//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Text", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Agricultural and industrial exchange of Ukraine”.
        /// </summary>
        internal static string text_business_offer_long_title {
            get {
                return ResourceManager.GetString("text_business_offer_long_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///        &lt;h3&gt;“Agricultural and industrial exchange of Ukraine”&lt;/h3&gt;
        ///        &lt;h1&gt;Commercial proposal&lt;/h1&gt;
        ///        &lt;p&gt;You are kindly requested by Agricultural and Industrial exchange of Ukraine to review our commercial proposal for mutually advantageous cooperation. The present proposal will be couched on the basis of our possibilities and involving your investments. The current economic and political situation in Ukraine is rather complicated and demands profound changes. In spite on complicated prob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_business_offer_text {
            get {
                return ResourceManager.GetString("text_business_offer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commercial.
        /// </summary>
        internal static string text_business_offer_title {
            get {
                return ResourceManager.GetString("text_business_offer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odessa.
        /// </summary>
        internal static string text_contacts_address_city {
            get {
                return ResourceManager.GetString("text_contacts_address_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        internal static string text_contacts_address_lable {
            get {
                return ResourceManager.GetString("text_contacts_address_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 76 Bazarna St.
        /// </summary>
        internal static string text_contacts_address_street {
            get {
                return ResourceManager.GetString("text_contacts_address_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine:.
        /// </summary>
        internal static string text_contacts_country {
            get {
                return ResourceManager.GetString("text_contacts_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@ai-exchange.com.ua.
        /// </summary>
        internal static string text_contacts_email {
            get {
                return ResourceManager.GetString("text_contacts_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        internal static string text_contacts_email_lable {
            get {
                return ResourceManager.GetString("text_contacts_email_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +(380) 66 847-23-33.
        /// </summary>
        internal static string text_contacts_phone {
            get {
                return ResourceManager.GetString("text_contacts_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: .
        /// </summary>
        internal static string text_contacts_phone_lable {
            get {
                return ResourceManager.GetString("text_contacts_phone_lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        internal static string text_contacts_title {
            get {
                return ResourceManager.GetString("text_contacts_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us now.
        /// </summary>
        internal static string text_contact_us {
            get {
                return ResourceManager.GetString("text_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Agricultural and industrial exchange of Ukraine”.
        /// </summary>
        internal static string text_cooperation_offer_long_title {
            get {
                return ResourceManager.GetString("text_cooperation_offer_long_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    &lt;div&gt;
        ///      &lt;h3&gt;“Agricultural and industrial exchange of Ukraine”&lt;/h3&gt;
        ///      &lt;h1&gt;Cooperation proposal&lt;/h1&gt;
        ///      &lt;p&gt;Up to 2014 the whole economic movement of Ukraine was crippled by the supreme government, which precluded to accumulate and to develop economic potential by their corrupted subunits, thus expanding economic policy in Ukraine does not exist. In addition, such situation has extended on different economical branches: power industry, agricultural sector, logistic directions, road junction [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_cooperation_offer_text {
            get {
                return ResourceManager.GetString("text_cooperation_offer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cooperation.
        /// </summary>
        internal static string text_cooperation_offer_title {
            get {
                return ResourceManager.GetString("text_cooperation_offer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agricultural and industrial exchange.
        /// </summary>
        internal static string text_inc_title {
            get {
                return ResourceManager.GetString("text_inc_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mailto://info@ai-exchange.com.ua.
        /// </summary>
        internal static string uri_contacts_email {
            get {
                return ResourceManager.GetString("uri_contacts_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/.
        /// </summary>
        internal static string uri_facebook {
            get {
                return ResourceManager.GetString("uri_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.linkedin.com/.
        /// </summary>
        internal static string uri_linkedin {
            get {
                return ResourceManager.GetString("uri_linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://twitter.com/.
        /// </summary>
        internal static string uri_twitter {
            get {
                return ResourceManager.GetString("uri_twitter", resourceCulture);
            }
        }
    }
}
